language: go
go:
- master

before_install:
- go get ${gobuild_args} ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/mitchellh/gox

script:
- go test -coverprofile=coverage.out -coverpkg=./,./cmd/... ./...
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
- make 

before_deploy:
  - git tag -f latest
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh latest
  - git remote remove gh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  name: latest
  overwrite: true
  tag_name: latest
  file_glob: true
  file: build/*.tar.gz
  target_commitish: $TRAVIS_COMMIT
  on:	  
    branch: master
